# Common configurations which a user might want to override
# For more information on what each configuration key and value does, check `default.toml`.
[server]
app_port = 8080
metrics_port = 8080

[database]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = ""
database = "postgres"

[auth]
secret = ""
